extends SceneTree
## Regenerate the baked authored-level table. LevelGen verifies every board and
## the result is deterministic, so we cache it into source: no per-level solver
## stall at runtime, and the 40 authored puzzles are frozen against future
## generator / solver tweaks.
##
##   godot --headless --path . --script res://tools/bake_levels.gd > game/level_data.gd

const Levels := preload("res://game/levels.gd")
const LevelGen := preload("res://game/level_gen.gd")

# Generate straight from the stage knobs (NOT Levels.build, which reads the
# baked table this script writes) so a re-bake is independent.
func _gen(i: int) -> Dictionary:
	if Levels.HAND_LEVELS.has(i):
		var h: Dictionary = (Levels.HAND_LEVELS[i] as Dictionary).duplicate(true)
		h["par"] = 0
		h["exact"] = false
		return h
	var s: Dictionary = Levels.STAGES[i]
	return LevelGen.generate(s["colors"], s["extra"], 4100 + i * 17, float(s.get("scr", 1.0)))

func _initialize() -> void:
	var out := "extends RefCounted\nclass_name LevelData\n"
	out += "## AUTO-GENERATED by tools/bake_levels.gd — do not edit by hand.\n"
	out += "## Frozen jars + verified par for the authored stages (0..%d).\n\n" % (Levels.count() - 1)
	out += "const STAGES := [\n"
	for i in Levels.count():
		var d: Dictionary = _gen(i)
		var jars: Array = d.get("jars", [])
		var par := int(d.get("par", 0))
		var exact := bool(d.get("exact", false))
		var jstrs: Array = []
		for j in jars:
			jstrs.append("[" + ",".join((j as Array).map(func(x): return str(x))) + "]")
		var js := "[" + ", ".join(jstrs) + "]"
		out += "\t{\"jars\": %s, \"par\": %d, \"exact\": %s},  # L%d\n" % [js, par, str(exact).to_lower(), i + 1]
	out += "]\n"
	printraw(out)
	quit()
